### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [wizarlock/CutUtility#2]
<s>1. `@Option(name = "-o", usage = "Output File")`- умеет парсить прямо в File/ Path. В целом, когда можно использовать более частные типы данных, более чётко удовлетворяющие особенностям поставленной задачи, лучше применять именно их;</s>

<s>2. `if ((inputFile.isEmpty()` - Вы вроде поддерживаете дальше здесь вариант с null, будет ли он сейчас работать? Кроме этого, у аннотаций есть required, со смежными проверками может помочь;</s>

<s>3. `} catch (IOException e) {
            e.printStackTrace();` - а это будет чем-то отличаться от дефолтной обработки? Кажется, если это так, то можно просто прокидывать наверх с помощью throws, ничего не изменится;</s>

<s>4. `String range` - кажется, нужно бы все-таки проверять предварительно regex-ом;</s>

5. `for (String line : list) {
                    for (int i = 0; i <= Integer.parseInt(range.replace("-", "")); i++) { 
                       newLine.append(line.charAt(i));
                        if (i == line.length() - 1) break;
                   }
                    newText.add(newLine.toString()); 
                   newLine.setLength(0);
                }`
 <s>от условий точно зависит только граница внутреннего цикла -> стоит отформировать общий, границы вычислять заранее (код станет более читаемым);</s> 

6. В `public static void cut(String inputName, String outputName, String range, boolean cKey, boolean wKey)` дублируется фрагмент кода, отвечающий за вывод -> стоит выделить отдельный приватный метод; Upd. Minor

<s>7. Для работы с ресурсами лучше использовать паттерн [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) - не надо руками закрывать + гарантирует закрытие даже в случае возникновения исключений;</s>

<s>8. `while (in.hasNext()) listOfString.add(in.nextLine());` - как Вы сейчас завершаете ввод с консоли?</s>
_______

Улучшения: 

<s>9. List<String> newText = cutText(Files.readAllLines(Paths.get(inputName)), range, cKey, wKey);  - в целом, информацию лучше бы обрабатывать построчно (что произойдет при работе с большими файлами?)</s>
10. Можно попробовать обобщить итоговые циклы для работы со словами/ символами с выделением приватного метода, принимающего в качестве аргумента реализацию [BiConsumer](https://docs.oracle.com/javase/8/docs/api/java/util/function/BiConsumer.html) (или аналог) (со звездочкой);

**Comment by wizarlock** [comment]
1) сделал
2) исправил, действительно не нужно
3) вынес в throws
4) теперь проверяю
5) сделал отдельный метод
6) записал получше, теперь повторений нет
7) теперь использую
8) ctrl + d
9) вроде теперь делаю построчно, если правильно Вас понял
10) не очень понимаю, куда это и чем оно мне поможет

**Comment by Suntrie** [comment]
11. `new parser.Parser().parseArguments(arguments);` - полное имя класса требуется в основном только тогда, когда у нас есть совпадения (2 класса для вывода информации об объекте, например, в качестве строчки справочника и детальной;
12. new CmdLineException("The entered data is not satisfactory"); - deprecated, чем заменить, можно посмотреть в доках.

**Comment by Suntrie** [comment]
10 - пример использования BiConsumer ("his is a functional interface and can therefore be used as the assignment target for a lambda expression or method reference") можно посмотреть здесь: https://javanerd.ru/%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-java/%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D1%8B-%D0%B2-java-8/

Здесь это, судя по всему, хорошего выигрыша действительно не даст.

**Comment by wizarlock** [comment]
11) исправил
12) заменил на IllegalArgumentException
